#!/bin/sh
shout() { echo "package/build-doc: $*" >&2; }
barf() { shout "fatal: $*"; exit 111; }

usage() {
  shout "usage: package/build-doc [ --help -F -- ] [ target ... ]"
  exit 100
}


#### MAIN

test -d package || barf "no package directory"

remove=""
while test $# -gt 0
do
  case "$1" in
    -F)
      remove="-F"
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      usage
      ;;
    *)
      break
      ;;
  esac
done

if test 0 -eq $#
then
  exec package/create $remove compile-doc doc build target \
    `awk '$1{print $1}' < src/build=d`
fi

exec package/create $remove compile-doc doc build target "$@"

barf "cannot compile $*"

