#!/bin/sh
shout() { echo "package/docs: $*" >&2; }
barf() { shout "fatal: $*"; exit 111; }

usage() {
  shout "usage: package/docs [ --help -F -- ] [ target ... ]"
  exit 100
}

#### MAIN

test -d package || barf "no package directory"

remove=""
while test $# -gt 0
do
  case "$1" in
    -F)
      remove="-F"
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      usage
      ;;
    *)
      break
      ;;
  esac
done

if test 0 -eq $#
then
  exec package/create $remove compile-doc doc make \
    `awk '$1{print $1}' < doc/build=d`
fi

exec package/create $remove compile-doc doc make "$@"

exit 111

