#!/bin/sh
shout() { echo "package/install: $@" >&2; }
barf() { shout "fatal: $@"; exit 111; }
safe() { "$@" || barf "cannot $@"; }

#### MAIN

safe package/compile
safe package/upgrade
safe package/run

exit 0
